import type { Value } from '@/types/pillars';

export const VALUES: Value[] = [
  { id: 0, name: 'Accountability', definition: 'Owning your actions and their consequences', detail: 'Taking responsibility without deflecting blame onto others.' },
  { id: 1, name: 'Achievement', definition: 'Reaching meaningful goals through effort', detail: 'The drive to accomplish things that matter and feel proud of results.' },
  { id: 2, name: 'Adaptability', definition: 'Adjusting well to change and uncertainty', detail: 'Staying effective and grounded when circumstances shift.' },
  { id: 3, name: 'Adventure', definition: 'Seeking new experiences and taking bold risks', detail: 'Finding life most alive at the edge of the unknown.' },
  { id: 4, name: 'Altruism', definition: 'Putting others\' needs genuinely before your own', detail: 'Acting selflessly without expecting recognition or return.' },
  { id: 5, name: 'Ambition', definition: 'Striving hard to reach high aspirations', detail: 'Pushing beyond comfort to build something significant.' },
  { id: 6, name: 'Authenticity', definition: 'Being genuinely yourself, not performing for others', detail: 'Aligning how you live with who you actually are.' },
  { id: 7, name: 'Balance', definition: 'Sustaining harmony across different parts of life', detail: 'Keeping work, rest, relationships, and self in healthy proportion.' },
  { id: 8, name: 'Beauty', definition: 'Noticing and creating what is aesthetically moving', detail: 'Bringing attention and care to form, craft, and sensory richness.' },
  { id: 9, name: 'Being the best', definition: 'Pursuing excellence to outperform others', detail: 'Driven not just to do well, but to lead and win.' },
  { id: 10, name: 'Belonging', definition: 'Feeling accepted and part of something larger', detail: 'Being genuinely welcomed for who you are.' },
  { id: 11, name: 'Career', definition: 'Building a meaningful and successful professional life', detail: 'Investing in work as a central expression of purpose and identity.' },
  { id: 12, name: 'Caring', definition: 'Showing warmth and concern for others\' wellbeing', detail: 'Attending to people\'s feelings and needs with genuine interest.' },
  { id: 13, name: 'Collaboration', definition: 'Achieving more by working well with others', detail: 'Valuing what emerges from collective effort over solo work.' },
  { id: 14, name: 'Commitment', definition: 'Following through on what you promised or started', detail: 'Staying the course when things get hard or boring.' },
  { id: 15, name: 'Community', definition: 'Investing in the places and groups around you', detail: 'Finding identity and purpose through local connection.' },
  { id: 16, name: 'Compassion', definition: 'Feeling others\' pain and acting to ease it', detail: 'Moved by suffering, not just acknowledging it from a distance.' },
  { id: 17, name: 'Competence', definition: 'Being skilled and capable at what you do', detail: 'Taking pride in genuine expertise and doing things well.' },
  { id: 18, name: 'Confidence', definition: 'Trusting your own judgment and abilities', detail: 'Acting decisively without needing constant external validation.' },
  { id: 19, name: 'Connection', definition: 'Building genuine closeness with other people', detail: 'Feeling truly seen and knowing others deeply.' },
  { id: 20, name: 'Contentment', definition: 'Finding peace with what you have', detail: 'Not chasing more as a condition for feeling okay.' },
  { id: 21, name: 'Contribution', definition: 'Adding value to something beyond yourself', detail: 'Leaving things better than you found them.' },
  { id: 22, name: 'Cooperation', definition: 'Working harmoniously for shared outcomes', detail: 'Prioritising collective smooth function over individual agenda.' },
  { id: 23, name: 'Courage', definition: 'Acting rightly even when it\'s frightening or costly', detail: 'Not the absence of fear, but moving forward through it.' },
  { id: 24, name: 'Creativity', definition: 'Making and expressing what didn\'t exist before', detail: 'Bringing new ideas, forms, or solutions into being.' },
  { id: 25, name: 'Curiosity', definition: 'Loving to learn and explore without a fixed agenda', detail: 'Drawn to questions more than needing answers.' },
  { id: 26, name: 'Dignity', definition: 'Treating every person as inherently worthy', detail: 'Refusing to demean or be demeaned.' },
  { id: 27, name: 'Diversity', definition: 'Valuing difference in people, perspectives, and cultures', detail: 'Seeing variety as a strength, not a problem to manage.' },
  { id: 28, name: 'Environment', definition: 'Protecting and caring for the natural world', detail: 'Treating ecological health as a genuine priority, not an afterthought.' },
  { id: 29, name: 'Efficiency', definition: 'Achieving goals with minimum wasted effort', detail: 'Good work without unnecessary friction.' },
  { id: 30, name: 'Equality', definition: 'Everyone deserves the same fundamental rights and opportunities', detail: 'Active commitment to fairness, not just passive acceptance.' },
  { id: 31, name: 'Ethics', definition: 'Acting according to a principled moral framework', detail: 'Thinking carefully about what is right, not just what is allowed.' },
  { id: 32, name: 'Excellence', definition: 'Doing things to the highest possible standard', detail: 'Not settling for good enough when better is achievable.' },
  { id: 33, name: 'Fairness', definition: 'Treating people justly, without favouritism', detail: 'Applying the same standards consistently to everyone.' },
  { id: 34, name: 'Faith', definition: 'Trusting in something larger than what you can prove', detail: 'Living in relationship with the sacred or transcendent.' },
  { id: 35, name: 'Family', definition: 'Deep commitment to the people closest to you', detail: 'Protecting and investing in your most intimate relationships.' },
  { id: 36, name: 'Financial stability', definition: 'Having enough resources to feel secure', detail: 'Not worrying about money as a baseline condition for wellbeing.' },
  { id: 37, name: 'Forgiveness', definition: 'Releasing resentment and making room for repair', detail: 'Not carrying grudges as a way of life.' },
  { id: 38, name: 'Freedom', definition: 'Living on your own terms without undue constraint', detail: 'Autonomy over how you spend your time and make choices.' },
  { id: 39, name: 'Friendship', definition: 'Deep bonds of mutual care and understanding', detail: 'People who choose each other and show up over time.' },
  { id: 40, name: 'Fun', definition: 'Making room for lightness, play, and enjoyment', detail: 'Life should feel good, not just productive.' },
  { id: 41, name: 'Future generations', definition: 'Protecting what those who come after will inherit', detail: 'Making decisions with an eye beyond your own lifetime.' },
  { id: 42, name: 'Generosity', definition: 'Giving freely of your time, money, or attention', detail: 'Abundance mindset — enough to share without keeping score.' },
  { id: 43, name: 'Giving back', definition: 'Returning value to those or places that shaped you', detail: 'A sense of debt paid forward through action.' },
  { id: 44, name: 'Grace', definition: 'Responding with poise and kindness under pressure', detail: 'Elegant in difficulty, not defensive or small.' },
  { id: 45, name: 'Gratitude', definition: 'Recognising and appreciating what you have', detail: 'Noticing gifts rather than cataloguing deficits.' },
  { id: 46, name: 'Growth', definition: 'Continually developing and becoming more capable', detail: 'The process of improving matters as much as the results.' },
  { id: 47, name: 'Harmony', definition: 'Living in peace with those around you', detail: 'Avoiding unnecessary conflict and seeking smooth coexistence.' },
  { id: 48, name: 'Health', definition: 'Taking care of your body and mind', detail: 'Physical and mental wellbeing as a genuine priority.' },
  { id: 49, name: 'Home', definition: 'Creating a place that truly feels like yours', detail: 'Sanctuary, roots, and belonging in a physical place.' },
  { id: 50, name: 'Honesty', definition: 'Telling the truth even when it\'s uncomfortable', detail: 'Not distorting reality to manage others\' reactions.' },
  { id: 51, name: 'Hope', definition: 'Believing things can improve and holding on', detail: 'A disposition toward the future that sustains action.' },
  { id: 52, name: 'Humility', definition: 'Knowing your limits and staying open to being wrong', detail: 'Not needing to be the smartest person in the room.' },
  { id: 53, name: 'Humor', definition: 'Finding and sharing what is genuinely funny', detail: 'Laughter as a tool for connection, perspective, and relief.' },
  { id: 54, name: 'Inclusion', definition: 'Ensuring no one is left outside or unseen', detail: 'Actively making space, not just tolerating difference.' },
  { id: 55, name: 'Independence', definition: 'Self-reliance and not depending on others to lead', detail: 'Trusting yourself to handle what comes.' },
  { id: 56, name: 'Initiative', definition: 'Moving first without waiting to be asked', detail: 'Seeing what needs doing and doing it.' },
  { id: 57, name: 'Integrity', definition: 'Living consistently according to your values', detail: 'What you do when no one is watching matches what you say you believe.' },
  { id: 58, name: 'Intuition', definition: 'Trusting your instincts as a source of knowledge', detail: 'Pattern recognition that runs faster than conscious reasoning.' },
  { id: 59, name: 'Job security', definition: 'Stable employment as a foundation for life', detail: 'Knowing your livelihood isn\'t suddenly at risk.' },
  { id: 60, name: 'Joy', definition: 'Experiencing moments of deep, uncomplicated happiness', detail: 'Delight that doesn\'t need to be earned.' },
  { id: 61, name: 'Justice', definition: 'Wrongs should be righted and people held accountable', detail: 'Not just fairness in the abstract but consequences that follow actions.' },
  { id: 62, name: 'Kindness', definition: 'Small acts of warmth and consideration toward others', detail: 'Making people feel slightly better than before they met you.' },
  { id: 63, name: 'Knowledge', definition: 'Understanding how things work and why', detail: 'The pursuit of truth and comprehension for its own sake.' },
  { id: 64, name: 'Leadership', definition: 'Guiding others toward a better outcome', detail: 'Taking responsibility for the direction others follow.' },
  { id: 65, name: 'Learning', definition: 'Growing through study, experience, and reflection', detail: 'Each situation is an opportunity to understand something new.' },
  { id: 66, name: 'Legacy', definition: 'What you leave behind when you\'re gone', detail: 'Building something that outlasts your presence.' },
  { id: 67, name: 'Leisure', definition: 'Time to rest, explore, and not produce', detail: 'Rest as a value, not just a recovery tool.' },
  { id: 68, name: 'Love', definition: 'Deep care and attachment for people in your life', detail: 'The fullest expression of human connection.' },
  { id: 69, name: 'Loyalty', definition: 'Standing by people and commitments over time', detail: 'Not leaving when things get difficult.' },
  { id: 70, name: 'Making a difference', definition: 'Changing things in a meaningful way', detail: 'Wanting your presence to have left a positive mark.' },
  { id: 71, name: 'Nature', definition: 'Connection with and care for the natural world', detail: 'Feeling at home outdoors, alive to the living world.' },
  { id: 72, name: 'Openness', definition: 'Genuinely considering other views and possibilities', detail: 'Willing to change your mind with good reason.' },
  { id: 73, name: 'Optimism', definition: 'Expecting things to go better than not', detail: 'A forward-facing attitude that sustains effort.' },
  { id: 74, name: 'Order', definition: 'Structure, clarity, and things in their right place', detail: 'Feeling better when things are organised and predictable.' },
  { id: 75, name: 'Parenting', definition: 'Raising children with love, wisdom, and intentionality', detail: 'The deepest investment and longest project of a life.' },
  { id: 76, name: 'Patience', definition: 'Tolerating delay and difficulty without resentment', detail: 'Staying calm when things take longer than you want.' },
  { id: 77, name: 'Patriotism', definition: 'Love of and commitment to your country', detail: 'Pride in national identity and contribution to your society.' },
  { id: 78, name: 'Peace', definition: 'Inner calm and freedom from conflict', detail: 'A settled quiet inside regardless of external noise.' },
  { id: 79, name: 'Perseverance', definition: 'Continuing through obstacles and setbacks', detail: 'Not giving up as a default response to difficulty.' },
  { id: 80, name: 'Personal fulfillment', definition: 'Living in a way that feels complete and true', detail: 'Being exactly who you are supposed to be.' },
  { id: 81, name: 'Power', definition: 'Having influence and control over outcomes', detail: 'The capacity to shape what happens.' },
  { id: 82, name: 'Pride', definition: 'Satisfaction in your accomplishments and identity', detail: 'Not arrogance, but earned confidence in what you\'ve built.' },
  { id: 83, name: 'Recognition', definition: 'Being seen and acknowledged for your contributions', detail: 'Matters to you that others notice and credit your work.' },
  { id: 84, name: 'Reliability', definition: 'Being someone others can count on', detail: 'Following through so people don\'t have to chase you.' },
  { id: 85, name: 'Resourcefulness', definition: 'Finding solutions with whatever is available', detail: 'Creative problem-solving when conventional options fail.' },
  { id: 86, name: 'Respect', definition: 'Treating others with dignity and taking them seriously', detail: 'Paying attention in a way that honours the other person.' },
  { id: 87, name: 'Responsibility', definition: 'Owning your obligations and their outcomes', detail: 'Not passing the buck when it lands at your feet.' },
  { id: 88, name: 'Risk-taking', definition: 'Accepting uncertainty for meaningful potential gain', detail: 'Comfortable with the possibility of loss in pursuit of reward.' },
  { id: 89, name: 'Safety', definition: 'Freedom from physical danger and harm', detail: 'Bodily security as a baseline condition for living.' },
  { id: 90, name: 'Security', definition: 'Stability and predictability in your circumstances', detail: 'Not living in anxiety about what tomorrow might bring.' },
  { id: 91, name: 'Self-discipline', definition: 'Controlling impulses to act in line with your goals', detail: 'Doing what you said you would even when you don\'t feel like it.' },
  { id: 92, name: 'Self-expression', definition: 'Showing who you are outwardly in the world', detail: 'Your inner life made visible through what you make or say.' },
  { id: 93, name: 'Self-respect', definition: 'Holding yourself in genuine positive regard', detail: 'Not needing others to tell you that you matter.' },
  { id: 94, name: 'Serenity', definition: 'A deep, settled calm that isn\'t easily disturbed', detail: 'Equanimity under conditions that would upset most people.' },
  { id: 95, name: 'Service', definition: 'Directing your efforts toward helping others', detail: 'A life oriented outward, not inward.' },
  { id: 96, name: 'Simplicity', definition: 'Removing what is unnecessary from your life', detail: 'Less clutter, less noise, more clarity.' },
  { id: 97, name: 'Spirituality', definition: 'Relating to something sacred or transcendent', detail: 'Life has a dimension that can\'t be weighed or measured.' },
  { id: 98, name: 'Sportsmanship', definition: 'Competing with grace and respecting opponents', detail: 'How you play matters as much as whether you win.' },
  { id: 99, name: 'Stewardship', definition: 'Caring for resources entrusted to you', detail: 'You are a caretaker, not an owner, of what passes through your hands.' },
  { id: 100, name: 'Success', definition: 'Achieving goals that society or you define as winning', detail: 'Reaching targets that signal genuine accomplishment.' },
  { id: 101, name: 'Teamwork', definition: 'The combined effort of a group beats any individual', detail: 'You trust and invest in collective performance.' },
  { id: 102, name: 'Thrift', definition: 'Using resources carefully and avoiding waste', detail: 'Frugality as a virtue, not a necessity.' },
  { id: 103, name: 'Time', definition: 'How you spend hours is how you spend your life', detail: 'Guarding attention as your most finite resource.' },
  { id: 104, name: 'Tradition', definition: 'Preserving practices passed down through generations', detail: 'Continuity with the past as a source of identity and meaning.' },
  { id: 105, name: 'Travel', definition: 'Exploring the world as a way of growing', detail: 'New places open new parts of you.' },
  { id: 106, name: 'Trust', definition: 'Confidence in others\' honesty and good faith', detail: 'You extend belief and expect it in return.' },
  { id: 107, name: 'Truth', definition: 'Reality matters and should be faced clearly', detail: 'You want the actual picture, not a comforting distortion.' },
  { id: 108, name: 'Understanding', definition: 'Genuinely grasping another\'s experience or point of view', detail: 'Going past your own frame to inhabit someone else\'s.' },
  { id: 109, name: 'Uniqueness', definition: 'Being singular and resisting the pressure to conform', detail: 'You are not interchangeable with other people.' },
  { id: 110, name: 'Usefulness', definition: 'Being practically valuable to others', detail: 'Your contribution is concrete and makes a real difference.' },
  { id: 111, name: 'Vision', definition: 'Seeing clearly where you want to go and guiding others there', detail: 'Directional clarity that pulls people forward.' },
  { id: 112, name: 'Vulnerability', definition: 'Sharing your inner life honestly and risking rejection', detail: 'Openness as strength, not weakness.' },
  { id: 113, name: 'Wealth', definition: 'Accumulating material resources and financial abundance', detail: 'Money as a meaningful goal in itself.' },
  { id: 114, name: 'Well-being', definition: 'A life that feels whole, healthy, and good', detail: 'Thriving across dimensions, not just surviving.' },
  { id: 115, name: 'Wholeheartedness', definition: 'Full engagement in what you do and who you are', detail: 'No half-measures, no hedged commitments.' },
  { id: 116, name: 'Wisdom', definition: 'Good judgment built from experience and reflection', detail: 'Knowing what to do in situations that have no rulebook.' },
];

export const N = VALUES.length; // 117

export const VALUE_MAP = new Map<number, Value>(VALUES.map(v => [v.id, v]));
